# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
labels:
  org.opencontainers.image.title: "Spliit App Add-on: Spliit App"
  org.opencontainers.image.description: "An instance of the Spliit app running from homeassistant"
  org.opencontainers.image.source: "https://github.com/ChristopherJohnston/spliit-app-homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  SPLIIT_VERSION: "1.9.0"
