# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Spliit
version: "1.0.0"
slug: spliit
description: Free and Open Source Alternative to Splitwise. Share expenses with your friends and family.
url: "https://github.com/ChristopherJohnston/spliit-app-homeassistant-addons/tree/main/spliit"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 3000
ingress_stream: true
hassio_role: manager
homeassistant_api: true
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
panel_icon: mdi:receipt-text-check
ports:
  3000/tcp: null
options:
  postgres_url: "postgresql://postgres:1234@localhost/spliit"
  postgres_url_non_pooling: "postgresql://postgres:1234@localhost/spliit"
schema:
  postgres_url: "str"
  postgres_url_non_pooling: "str"
image: "ghcr.io/ChristopherJohnston/{arch}-addon-spliit"
