# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Spliit
version: "1.0.9"
slug: spliit
description: Free and Open Source Alternative to Splitwise. Share expenses with your friends and family.
url: "https://github.com/ChristopherJohnston/spliit-app-homeassistant-addons/tree/main/spliit"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_stream: true
hassio_role: manager
homeassistant_api: true
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
panel_icon: mdi:receipt-text-check
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
options:
  postgres_url: "postgresql://postgres:1234@localhost/spliit"
  postgres_url_non_pooling: "postgresql://postgres:1234@localhost/spliit"

  expense_documents: false
  s3_bucket: ""
  s3_region: ""
  s3_key: ""
  s3_secret: ""

  s3_endpoint: ""

  receipt_extract: false
  category_extract: false
  openai_api_key: ""

  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
schema:
  postgres_url: "str"
  postgres_url_non_pooling: "str"

  expense_documents: "bool"
  s3_endpoint: "str"
  s3_bucket: "str"
  s3_region: "str"
  s3_key: "str"
  s3_secret: "str"

  receipt_extract: "bool"
  category_extract: "bool"
  openai_api_key: "str"

  ssl: "bool"
  certfile: "str"
  keyfile: "str"
image: "ghcr.io/christopherjohnston/{arch}-addon-spliit"
